updates desk (#13)

diff --git a/config/git/.git-hooks/pre-commit b/config/git/.git-hooks/pre-commit
--- a/config/git/.git-hooks/pre-commit
+++ b/config/git/.git-hooks/pre-commit
@@ -6,3 +6,8 @@ if [ "$branch" = "master" ]; then
   echo "You can't commit directly to master branch"
   exit 1
 fi
+
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
